site_name: SynBio Project Tutorials
site_url: https://UCB-BioE-Anderson-Lab.github.io/cloning-tutorials/
repo_url: https://github.com/UCB-BioE-Anderson-Lab/cloning-tutorials

theme:
  name: material
  logo: images/logo.png

nav:
  - Overview: index.md
  - Wetlab:
      - 1. Lab Safety: wetlab/safety.md
      - 2. Pipetting: wetlab/pipetting.md
      - 3. pP6 Experiment Introduction: wetlab/intro.md
      - 4. Polymerase Chain Reaction: wetlab/pcr.md
      - 5. Gel Electrophoresis: wetlab/gel.md
      - 6. Zymo Cleanup: wetlab/cleanup.md
      - 7. Assembly: wetlab/assembly.md
      - 8. Transformation: wetlab/transformation.md
      - 9. Colony Picking: wetlab/pick.md
      - 10. Miniprep: wetlab/miniprep.md
      - 11. Cycle Sequencing: wetlab/sequencing.md
      - 12. Measuring Fluorescence: wetlab/bestp.md
      - 13. Equipment Training: trainings/qr_training.md

  - Cloning Techniques:
      - 1. DNA Basics: construction/dna_basics.md
      - 2. Sequence Editing Tools: construction/sequence_tools.md
      - 3. Manual Product Prediction: construction/manual_prediction.md
      - 4. Simulation Tools: construction/simulation_tools.md
      - 5. Basic Cloning: construction/basic_cloning.md
      - 6. Gibson Assembly: construction/gibson.md
      - 7. Golden Gate Assembly: construction/golden_gate.md
      - 8. Site-Directed Mutagenesis: construction/mutagenesis.md
      - 9. Sequencing Confirmation: construction/sequencing_confirmation.md

  - Project Planning:
      - 1. Project Setup and Nomenclature: planning/project_setup.md
      - 2. Experimental Design Principles: planning/design_principles.md
      - 3. Sequence Retrieval and Analysis: planning/sequence_analysis.md
      - 4. Choosing a Fabrication Strategy: planning/oligo_design.md
      - 5. Simulation Tools: planning/cfs_simulation.md
      - 6. Inventory and Labsheets: planning/inventory_labsheets.md
      - 7. Ortholog Scan Project: planning/project_ispA.md

  - Tools:
      - Feature Extractor: tools/feature_extractor.md
      - Feature Manager: tools/feature_manager.md
      - Super Simulator: tools/supersimulator.md
      - Tabular Simulator: tools/tabular_simulator.md
      - Oligo Finder: tools/oligo_finder.md
      - Inventory Manager: tools/inventory_manager.md

  - Training & Certification:
      - "-80 Freezer": trainings/minus_80.md
      - "Chemical Cabinets": trainings/chemical_cabinets.md
      - "Allegra Centrifuge": trainings/allegra_v15r.md
      - "Qsonica Sonicator": trainings/q500_sonicator.md
      - "Microwave": trainings/microwave.md
      - "Echotherm": trainings/echotherm.md
      - "Proflex": trainings/proflex.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - footnotes
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

plugins:
  - search
  - table-reader
  - awesome-pages
  # - pdf-export:
  #     combined: true
  #     media_type: print
  
extra_javascript:
  - js/launch-apps-script.js
  - js/progress_manager.js
  
extra_css:
  - css/custom.css


extra:
  analytics:
    provider: google
    property: G-2PJLYHVLQ1
  copyright: "© 2025 University of California, Berkeley"
