site_name: Cloning Tutorials
site_url: https://UCB-BioE-Anderson-Lab.github.io/cloning-tutorials/
repo_url: https://github.com/UCB-BioE-Anderson-Lab/cloning-tutorials

theme:
  name: material

nav:
  - Wetlab:
      - 1. pP6 Experiment Introduction: pp6_intro.md
      - 2. Pipetting: pp6_pipetting.md
      - 3. PCR Setup: pp6_pcr.md
      - 4. Gel Electrophoresis: pp6_gel.md
      - 5. Zymo Cleanup: pp6_cleanup.md
      - 6. Golden Gate Assembly: pp6_assembly.md
      - 7. Transformation: pp6_transformation.md
      - 8. Colony Picking: pp6_pick.md
      - 9. Miniprep: pp6_miniprep.md
      - 10. Sanger Sequencing: pp6_sequencing.md
      - 11. Closeout and Documentation: pp6_closeout.md
  - Cloning Techniques:
      - 1. DNA Basics: dna_basics.md
      - 2. Sequence Editing Tools: sequence_tools.md
      - 3. Manual Product Prediction: manual_prediction.md
      - 4. Simulation Tools: simulation_tools.md
      - 5. Basic Cloning: basic_cloning.md
      - 6. Gibson Assembly: gibson.md
      - 7. Golden Gate Cloning: golden_gate.md
      - 8. BioBricks and Assembly: biobricks.md
      - 9. Short Parts Construction: short_parts.md
      - 10. Sequencing Analysis: sequencing.md
  - Project Planning:
      - 1. Project Setup and Nomenclature: project_setup.md
      - 2. Experimental Design Principles: design_principles.md
      - 3. Sequence Retrieval and Analysis: sequence_analysis.md
      - 4. Choosing a Fabrication Strategy: oligo_design.md
      - 5. Simulation Tools: cfs_simulation.md
      - 6. Inventory and Labsheets: inventory_labsheets.md
      - 7. Ortholog Scan Project: project_ispA.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - footnotes
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

plugins:
  - search
  - table-reader
  - awesome-pages
  
extra_javascript:
  - js/C6-Align.js
  - js/C6-Gene.js
  - js/C6-Oligos.js
  - js/C6-Seq.js
  - js/C6-Sim.js
  - js/C6-Utils.js
  - js/progress_manager.js

extra_css:
  - css/custom.css
