/**
 * TPcon6 - BestP labsheet master: corrections
 *
 * Sheet: https://docs.google.com/spreadsheets/d/14h6yquAQm3saaf_VOA-ytxYs5q6JbKaVCsslLpKXX6w
 *
 * HOW TO RUN
 *   Extensions > Apps Script from the sheet, paste this in, or `clasp push`.
 *   Leave DRY_RUN = true the first time. It writes nothing and logs a diff of
 *   every change it would make. Read the log, then set DRY_RUN = false.
 *
 * BEFORE ANYTHING ELSE — check whether these sheets are generated.
 *   The `clones` tab says "Autogenerated, do not edit", and the sample tables on
 *   Transform / Pick / Assay are derived from `entry`. If an existing Apps Script
 *   also emits the *protocol text*, then editing these cells is temporary and the
 *   real fix belongs in that script's source. Run `clasp clone` / `clasp pull` on
 *   the bound project and grep it for "Spectramax" before running this.
 *
 * Nothing here inserts or deletes rows, so no ranges, formulas or print layouts
 * move. Every edit is a single cell, and each one verifies the current contents
 * before touching it — if the text has changed since 2026-08-28, that edit is
 * skipped and reported rather than overwritten.
 */

const SHEET_ID = '14h6yquAQm3saaf_VOA-ytxYs5q6JbKaVCsslLpKXX6w';
const DRY_RUN = true;

/**
 * Confirmed by JCA: the instrument is a Tecan M Nano. The Assay protocol still says
 * "Spectramax", which is a different manufacturer's machine, and the Fluorescence header
 * says "SAFIRE II" because that block is old example data. Both are wrong.
 */
const INSTRUMENT_NAME = 'Tecan M Nano';

/**
 * Read settings, copied from the header block of the `Fluorescence` sheet.
 * They live there today, inside the example data — and that sheet is labelled
 * "Paste your data over this data", so a student destroys the settings in their
 * own copy the moment they paste a real read. Putting them in the protocol text
 * is the point of this edit.
 */
const READ_SETTINGS =
  'Fluorescence Top; excitation 483 nm, emission 525 nm, both bandwidths 20 nm; ' +
  'gain 40 (manual); 20 reads; high sensitivity flash; integration 40 µs; ' +
  'Z 11019 µm; target 30 °C; plate definition COS96ft.';

function fixBestPLabsheet() {
  if (!INSTRUMENT_NAME) {
    throw new Error('Set INSTRUMENT_NAME before running — see the comment above it.');
  }

  const ss = SpreadsheetApp.openById(SHEET_ID);
  const log = [];

  function edit(sheetName, a1, expected, next) {
    const sheet = ss.getSheetByName(sheetName);
    if (!sheet) { log.push('!  no sheet named ' + sheetName); return; }
    const range = sheet.getRange(a1);
    const current = range.getValue();

    if (current === next) { log.push('=  ' + sheetName + '!' + a1 + '  already correct'); return; }
    if (current !== expected) {
      log.push('!  ' + sheetName + '!' + a1 + '  SKIPPED, contents have changed' +
               '\n     expected: ' + JSON.stringify(expected) +
               '\n     found:    ' + JSON.stringify(current));
      return;
    }
    log.push('-  ' + sheetName + '!' + a1 + '  ' + JSON.stringify(current) +
             '\n+  ' + sheetName + '!' + a1 + '  ' + JSON.stringify(next));
    if (!DRY_RUN) range.setValue(next);
  }

  // 1. The instrument is named wrongly in two places.
  edit('Assay', 'B16',
       'Turn on the Spectramax instrument',
       'Turn on the ' + INSTRUMENT_NAME + ' instrument');
  edit('Assay', 'B23',
       'Shut down the Spectramax and computer',
       'Shut down the ' + INSTRUMENT_NAME + ' and computer');

  // 2. Carry the read settings in the protocol, where they survive a paste.
  const step4 = "Put the plate in the instrument and measure 'fluorescein' fluorescence";
  edit('Assay', 'B20', step4, step4 + '. Settings: ' + READ_SETTINGS);

  // 3. Pick is numbered 1, 2, 3, 4, 6, 7 — there is no step 5.
  edit('Pick', 'A20', '6)', '5)');
  edit('Pick', 'A21', '7)', '6)');

  Logger.log((DRY_RUN ? 'DRY RUN — nothing was written.\n\n' : 'CHANGES WRITTEN.\n\n') +
             log.join('\n'));
}

/**
 * For after filming. `Assay!A3` is the label "Watch the video:" and `B3` beside
 * it is empty — that is the slot the bestp_tecan clip fills.
 *
 * Call from the editor with the URL, e.g.
 *   setAssayVideoLink('https://youtu.be/XXXXXXXXXXX')
 */
function setAssayVideoLink(url) {
  if (!url) throw new Error('Pass the video URL.');
  const ss = SpreadsheetApp.openById(SHEET_ID);
  const cell = ss.getSheetByName('Assay').getRange('B3');
  const current = cell.getValue();
  if (current && current !== url) {
    Logger.log('B3 already holds ' + JSON.stringify(current) + ' — not overwriting.');
    return;
  }
  if (DRY_RUN) { Logger.log('DRY RUN — would set Assay!B3 to ' + url); return; }
  cell.setValue(url);
  Logger.log('Assay!B3 set to ' + url);
}
